### ISSUE TITLE
Cutflow comparing Run 1 and 2 ntuples

### ISSUE THREAD

**Issue by manuelfs** [umd-lhcb/lhcb-ntuples-gen#24]
Our goal is to understand why we were getting 5 times more events per ifb in Run 2 than in Run 1. We would have expected an increase of about 2 due to the cross section, and less than 2 thanks to the improved trigger.

To study this, we should compare the following in Runs 1 and 2:
- [x] L0 efficiency
- [x] HLT efficiency
- [x] Stripping line efficiency
- [x] Efficiency of each of the selection cuts applied in the DaVinci script

The first three items require a denominator that contains event that are not saved in data. Thus, they can only be estimated with orthogonal trigger/stripping lines, or in MC. 

The last item is a bit ill-defined, as the main purpose of the DaVinci script is to reconstruct all the particles, which is done simultaneously (there may be additional event-level cuts). 

Later, we decided that we need to do these 2 additional studies:

- [x] Repeat the cocktail MC study with high stats
- [x] Study the partial cut flow on real data

Later than later, we decide that it is worth breaking out the L0 and HLT 1 triggers and study the efficiencies of various trigger paths (L0 -> HLT 1 -> HLT 2).

- [x] Select and add L0 & HLT 1 branches to MC ntuples
- [x] Generate a break-out cut flow

One possibility would be to write a DaVinci script that runs on cocktail MC that does the following
* It saves *all* events
* Adds branches that tell us whether the given event passed L0, HLT, and the stripping line cuts
* Adds branches that indicate if each of the particles reconstructed in the DaVinci script (mu, K, pi-, pi+, D, D*) exist in the event
* Adds branches that indicates if any other cut applied in the standard DaVinci script is passed

**Comment by yipengsun** [comment]
## General idea
1. Since we are using **unfiltered** cocktail MC, we need to run stripping-line-equivalent selection on every event. Log file is saved
2. We reconstruct the events passing the stripping-line-equivalent condition, and save the `L0`, `HLT` decision for these events
3. From the log file, we figure out the `L0` efficiencies **Problem: Don't see a separate `L0` report**
4. From the log file we figure out the cut efficiencies. This includes both **Stripping line** and **additional cuts imposed by us**

It's worth noting that I saved `L0` and `HLT` decisions in the generated n-tuple. But I don't think these are useful.

## Input
I'm using `.dst` files in `run2-b2D0MuXB2DMuForTauMuLine/data/mc-mag_down-py8-sim09b-Bd2D0XMuMu-D0_cocktail`. These are **unfiltered**.

## Procedure
1. Generate a n-tuple inside docker environment with
   ```
   ./run.sh reco_Dst.py conds/cond-mc-mag_down-sim09b-Bd2D0XMuMu-D0_cocktail.py | tee log.txt
   ```
2. Parse the log with
   ```
   ../utils/davinci_log_parser.py parsed.yml log.txt
   ```

## Output
- The raw log is saved in `run2-b2D0MuXB2DMuForTauMuLine/logs/20200221-run2-reco_Dst.log`
- The parsed log is saved in `run2-b2D0MuXB2DMuForTauMuLine/data/mc-mag_down-py8-sim09b-Bd2D0XMuMu-D0_cocktail.yml`

**Comment by yipengsun** [comment]
I think the tool Phoebe was talking about is called `HltDecReport`. My impression is that I copied various sample code using that tool (Include Jack's),. and none of them give me any useful output.

**Comment by yipengsun** [comment]
| Name of the cut | Yield of run 1 | Yield of run 1 | Efficiency run 1 | Efficiency run 2 | Double Ratio |
|---|---|---|---|---|---|

**Comment by yipengsun** [comment]
I think the `TEfficiency` calculation can be made in Python with the following package: https://www.statsmodels.org/stable/generated/statsmodels.stats.proportion.proportion_confint.html

**Comment by yipengsun** [comment]
If we use the incorrect `sel_unstripped_Mu`, we have a more sensible result:
```yaml
SELECT:Phys/StdAllNoPIDsKaons:
    input: 26633
    output: 26619
SELECT:Phys/StdAllNoPIDsPions:
    input: 26619
    output: 26619
SelMyD0:
    input: 26619
    output: 2343
SELECT:Phys/StdAllLoosePions:
    input: 2343
    output: 2343
SelMyDst:
    input: 2343
    output: 1231
SELECT:Phys/StdAllNoPIDsMuons:
    input: 1231
    output: 1231
SelMyB0:
    input: 741
    output: 224
SelMyRefitB02DstMu:
    input: 224
    output: None
```
