### ISSUE TITLE
Make cutflow MC bare work again

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#73]
Our latest production of cutflow bare doesn't seem to have right numbers. I'll investigate them further to re-produce a final version of the cutflow MC bare ntuples.

I also want to use this opportunity to remove all obsolete flags.

## Run 1
- The Muon-TIS filtering was turned on for run 1, resulting in a ~97% efficiency for L0 trigger

## Run 2
- Additional HLT2 cut always applied

**Comment by yipengsun** [comment]
For run 1, after the bugfix, the cutflow looks like this:
```yml
Total events:
    input: 17894
    output: 17894
Relaxed $D^0 \mu$ combo:
    input: 3920
    output: 2417
$D^{*+} \rightarrow D^0 \pi^+$:
    input: 2417
    output: 2242
$\bar{B}^0 \rightarrow D^{*+} \mu^-$:
    input: 2109
    output: 2045
L0:
    input: 2045
    output: 806
Hlt1:
    input: 806
    output: 400
Hlt2:
    input: 400
    output: 163
Stripping:
    input: 163
    output: 80
DaVinci $D^* \mu$ cuts:
    input: 80
    output: 57
Offline $D^0$ cuts:
    input: 57
    output: 32
Offline $\mu$ cuts:
    input: 32
    output: 25
Offline $D^* \mu$ combo cuts:
    input: 25
    output: 25
```

**Comment by yipengsun** [comment]
For updated run 2 bare, here's the cutflow (the generation of the cutflow ntuples is now very slow, consistent w/ my old impression). Now all trigger cuts have lower efficiency compared to run 1:
```yml
Total events:
    input: 26633
    output: 26633
Relaxed $D^0 \mu$ combo:
    input: 22819
    output: 9154
$D^{*+} \rightarrow D^0 \pi^+$:
    input: 9154
    output: 8699
$\bar{B}^0 \rightarrow D^{*+} \mu^-$:
    input: 8351
    output: 8119
L0:
    input: 8119
    output: 2809
Hlt1:
    input: 2809
    output: 1310
Hlt2:
    input: 1310
    output: 421
Stripping:
    input: 421
    output: 339
DaVinci $D^* \mu$ cuts:
    input: 339
    output: 196
Offline $D^0$ cuts:
    input: 196
    output: 58
Offline $\mu$ cuts:
    input: 58
    output: 49
Offline $D^* \mu$ combo cuts:
    input: 49
    output: 43
```
