### ISSUE TITLE
Validate global and skim cuts for D0, D* regular data templates

### ISSUE THREAD

**Issue by yipengsun** [umd-lhcb/lhcb-ntuples-gen#88]
Previous we validated the global step-2 cuts, which apply cuts to **Phoebe's step-1 ntuple** and compare the output w/ Phoebe's step-2.

Note that Pheobe's step-2 doesn't seem to contain skim booleans like `is_iso` or `is_1os`, so I don't think we have an anchor point from the ntuple directly. These flags are mostly for MC:

```
  flag2011: bool
  flagBadMu: double
  flagBadSoln: double
  flagBmu: double
  flagComb: double
  flagD0mu: float
  flagDoubleD: double
  flagDstSB: double
  flagGhost: double
  flagTauonicD: double
  flagtaumu: double
```

However, what we can do is: Use **Phoebe's step-2 ntuple as input**, apply our skim cuts and build templates, then compare the template entry from Phoebe's run 1 (2011) template.

**Comment by yipengsun** [comment]
Here's all branches in Phoebe's step-2 ntuple:

```
ntp1:
  AntiISOnum: int32_t
  BDTmu: float
  B_MPTb: double
  B_TRUEP: double
  B_TRUEPT: double
  B_TRUEP_Z: double
  B_XY_ERR: double
  Btype: int32_t
  Chi: double
  Chi2: double
  CosFlightReco: double
  D0IP: double
  D0IPCHI2: double
  D0_DIRA_OWNPV: double
  D0_FD: double
  D0_M: double
  D0_P: double
  D0_PT: double
  DLLe: double
  DLLmu: double
  DMUDIRA: double
  DeltaChi2: double
  DstIDprod: double
  DstOk: double
  Dst_2010_minus_MC_MOTHER_ID: int32_t
  Dst_2010_minus_MC_MOTHER_KEY: int32_t
  Dst_ENDVERTEX_CHI2: double
  Dst_ID: int32_t
  Dst_M: double
  Dst_MC_MOTHER_ND: int32_t
  Dst_P: double
  Dst_PT: double
  Dst_TRUEID: int32_t
  Dst_mom: int32_t
  Dst_mom_m: double
  Dststtype: int32_t
  El: double
  El2: double
  ElR: double
  Elaltm: double
  Elaltp: double
  ElotherVtx: double
  Elsmear: double
  ElsmearG: double
  ElsmearK: double
  ElsmearK0: double
  ElsmearK0_eCut: double
  ElsmearK0_eSel: double
  ElsmearK_eCut: double
  ElsmearK_eSel: double
  Elsmearpi: double
  Elsmearpi0: double
  Elsmearpi0_eCut: double
  Elsmearpi0_eSel: double
  Elsmearpi_eCut: double
  Elsmearpi_eSel: double
  Elt: double
  Etaut: double
  FFweight: double
  FFweightALT: double
  FFweightu1m: double
  FFweightu1p: double
  FFweightu2m: double
  FFweightu2p: double
  FFweightu3m: double
  FFweightu3p: double
  FFweightu4m: double
  FFweightu4p: double
  FFweightu5m: double
  FFweightu5p: double
  FFweightu6m: double
  FFweightu6p: double
  FFweightu7m: double
  FFweightu7p: double
  FFweightu8m: double
  FFweightu8p: double
  FFweightu9m: double
  FFweightu9p: double
  FFweightuAm: double
  FFweightuAp: double
  FFweightv1m: double
  FFweightv1p: double
  FFweightv2m: double
  FFweightv2p: double
  FFweightv3m: double
  FFweightv3p: double
  FFweightv4m: double
  FFweightv4p: double
  FFweightvv1m: double
  FFweightvv1p: double
  FFweightvv2m: double
  FFweightvv2p: double
  FFweightvv3m: double
  FFweightvv3p: double
  GhostProb: double
  GsmearAngle: double
  HADDEC: bool
  HADTIS: bool
  HLTTCK: UInt_t
  Hlt1: bool
  Hlt1K: bool
  Hlt1TAL0K: bool
  Hlt1TAL0pi: bool
  Hlt1pi: bool
  Hlt2: bool
  IDprod: double
  ISOnum: int32_t
  JustDst: double
  KPID: double
  KPIDerror: double
  KPIDweight: double
  KPIDweight2: double
  K_P: double
  K_PT: double
  Kplus_P: double
  Kplus_rho: double
  L0: bool
  L0DUTCK: UInt_t
  MHD: double
  MUDEC: bool
  MUTIS: bool
  NNmu: double
  NShared: int32_t
  Nbody: int32_t
  Oldpi2mu_nonuBDTeCut: double
  Oldpi2mu_nonuBDTeSel: double
  Oldpi2mu_uBDTeCut: double
  Oldpi2mu_uBDTeSel: double
  P1: double
  PK2h: double
  PV_XY_ERR: double
  Pe2h: double
  PestZ: double
  Polarity: int16_t
  Pp2h: double
  Ppi2h: double
  Pu2h: double
  YTIS: bool
  YTOS: bool
  Y_BKGCAT: int32_t
  Y_BKGCAT_OLD: int32_t
  Y_DIRA_OWNPV: double
  Y_DISCARDMu_CHI2: double
  Y_ENDVERTEX_CHI2: double
  Y_ETA: double
  Y_FDCHI2_OWNPV: double
  Y_FD_OWNPV: double
  Y_IPCHI2_OWNPV: double
  Y_IP_OWNPV: double
  Y_M: double
  Y_MMERR: double
  Y_MsmearK: double
  Y_MsmearK0: double
  Y_MsmearK0_eCut: double
  Y_MsmearK0_eSel: double
  Y_MsmearK_eCut: double
  Y_MsmearK_eSel: double
  Y_Msmearpi: double
  Y_Msmearpi0: double
  Y_Msmearpi0_eCut: double
  Y_Msmearpi0_eSel: double
  Y_Msmearpi_eCut: double
  Y_Msmearpi_eSel: double
  Y_P: double
  Y_PT: double
  Y_SIGMA_IP: double
  Y_myDOCA: double
  Y_myDOCAchi2: double
  altM: double
  badSlowPi: double
  badSlowPiTau: double
  cmult100: int32_t
  cmult60: int32_t
  cpt60: double
  dxy: double
  dxy_err: double
  e2mu: double
  e2mu_nonuBDTeCut: double
  e2mu_nonuBDTeSel: double
  e2mu_uBDT: double
  e2mu_uBDTeCut: double
  e2mu_uBDTeSel: double
  e2notmu: double
  eratio_uBDT: double
  eventNumber: ULong64_t
  f_k: double
  f_p: double
  f_pi: double
  flag2011: bool
  flagBadMu: double
  flagBadSoln: double
  flagBmu: double
  flagComb: double
  flagD0mu: float
  flagDoubleD: double
  flagDstSB: double
  flagGhost: double
  flagTauonicD: double
  flagtaumu: double
  higherD0hel: double
  iBin: int32_t
  iBinK: int32_t
  iBinpi: int32_t
  isData: double
  ishigher: bool
  iso: double
  iso2: double
  iso_BDT: double
  iso_BDT2: double
  iso_BDT3: double
  iso_CHARGE: float
  iso_CHARGE2: float
  iso_CHARGE3: float
  iso_CHI2: double
  iso_DeltaM: double
  iso_NNk: float
  iso_NNk2: float
  iso_NNk3: float
  iso_NNkw: double
  iso_NNkw2: double
  iso_NNkw3: double
  iso_NNp: float
  iso_NNp2: float
  iso_NNp3: float
  iso_P: float
  iso_P2: float
  iso_P3: float
  iso_PE: float
  iso_PE2: float
  iso_PT: float
  iso_PT2: float
  iso_PT3: float
  iso_Type: float
  iso_Type2: float
  iso_Type3: float
  iso_clonevar: double
  k2k: double
  k2mu: double
  k2mu_nonuBDTeCut: double
  k2mu_nonuBDTeSel: double
  k2mu_uBDT: double
  k2mu_uBDTeCut: double
  k2mu_uBDTeSel: double
  k2notmu: double
  k2pi: double
  kWeight: double
  kWeightErr: double
  keepme: bool
  logDOCA: double
  mDD: double
  mDDnew: double
  mX_DD: double
  mXnew_DD: double
  m_corr: double
  m_nu1: double
  m_nu1altm: double
  m_nu1altp: double
  m_nu1otherVtx: double
  m_nu1smear: double
  m_nu1smearG: double
  m_nu1smearK: double
  m_nu1smearK0: double
  m_nu1smearK0_eCut: double
  m_nu1smearK0_eSel: double
  m_nu1smearK_eCut: double
  m_nu1smearK_eSel: double
  m_nu1smearpi: double
  m_nu1smearpi0: double
  m_nu1smearpi0_eCut: double
  m_nu1smearpi0_eSel: double
  m_nu1smearpi_eCut: double
  m_nu1smearpi_eSel: double
  m_nu2: double
  m_nuG: double
  m_nuR: double
  m_nuT: double
  matchChi2: double
  mcWeight: double
  mm_DD: double
  mm_mom: double
  momWeight: double
  muHAD: bool
  muIP: double
  muIPCHI2: double
  muPID: float
  muPIDerror: double
  muPIDweight: double
  muPIDweight_nonuBDT: double
  muPIDweight_nonuBDTeCut: double
  muPIDweight_nonuBDTeSel: double
  muPIDweight_uBDT: double
  muPIDweight_uBDTeCut: double
  muPIDweight_uBDTeSel: double
  muTOS: bool
  muVeto: bool
  mu_CosTheta: double
  mu_ETA: double
  mu_P: double
  mu_PT: double
  mu_PTb: double
  mu_PTsmearK: double
  mu_PTsmearK0: double
  mu_PTsmearK0_eCut: double
  mu_PTsmearK0_eSel: double
  mu_PTsmearK_eCut: double
  mu_PTsmearK_eSel: double
  mu_PTsmearpi: double
  mu_PTsmearpi0: double
  mu_PTsmearpi0_eCut: double
  mu_PTsmearpi0_eSel: double
  mu_PTsmearpi_eCut: double
  mu_PTsmearpi_eSel: double
  mu_PsmearK: double
  mu_PsmearK0: double
  mu_PsmearK0_eCut: double
  mu_PsmearK0_eSel: double
  mu_PsmearK_eCut: double
  mu_PsmearK_eSel: double
  mu_Psmearpi: double
  mu_Psmearpi0: double
  mu_Psmearpi0_eCut: double
  mu_Psmearpi0_eSel: double
  mu_Psmearpi_eCut: double
  mu_Psmearpi_eSel: double
  mu_has: bool
  mu_is: bool
  mu_isT: bool
  muplus_MC_MOTHER_ID: int32_t
  muplus_MC_MOTHER_KEY: int32_t
  muplus_MC_MOTHER_ND: int32_t
  muplus_TRUEID: int32_t
  muplus_rho: double
  nISO: int32_t
  nSPDhits: double
  nTracks: double
  noChi2: int32_t
  noDChi2: int32_t
  p2mu: double
  p2mu_nonuBDTeCut: double
  p2mu_nonuBDTeSel: double
  p2mu_uBDT: double
  p2mu_uBDTeCut: double
  p2mu_uBDTeSel: double
  p2notmu: double
  p2p: double
  pWeight: double
  pWeightErr: double
  pi2k: double
  pi2mu: double
  pi2mu_nonuBDTeCut: double
  pi2mu_nonuBDTeSel: double
  pi2mu_uBDT: double
  pi2mu_uBDTeCut: double
  pi2mu_uBDTeSel: double
  pi2notmu: double
  pi2pi: double
  piPID: double
  piPIDerror: double
  piPIDweight: double
  piPIDweight2: double
  piWeight: double
  piWeightErr: double
  pi_P: double
  pi_PT: double
  piminus0_P: double
  piminus_TRACK_Type: int32_t
  piminus_rho: double
  pislow_GhostProb: double
  pislow_IP: double
  pislow_IPCHI2: double
  pislow_P: double
  pislow_PT: double
  pislow_ProbNNk: double
  pislow_ismu: bool
  pislow_muAcc: bool
  pislow_rho: double
  q2: double
  q2R: double
  q2altm: double
  q2altp: double
  q2otherVtx: double
  q2smear: double
  q2smearG: double
  q2smearK: double
  q2smearK0: double
  q2smearK0_eCut: double
  q2smearK0_eSel: double
  q2smearK_eCut: double
  q2smearK_eSel: double
  q2smearpi: double
  q2smearpi0: double
  q2smearpi0_eCut: double
  q2smearpi0_eSel: double
  q2smearpi_eCut: double
  q2smearpi_eSel: double
  q2t: double
  q2tD: double
  reweighting_68: float
  reweighting_69_gen2: float
  reweighting_69_gen2_pt2: float
  reweighting_69_pt2: float
  reweighting_89: float
  reweighting_89_gen2: float
  reweighting_89_gen2_pt2: float
  reweighting_89_pt2: float
  reweighting_JpsiK09_v1: float
  reweighting_JpsiK09_v2: float
  runNumber: UInt_t
  selcounter: UInt_t
  simpleDstst: double
  tantheta: double
  tanthetaotherVtx: double
  thetaD: double
  thetaFlight: double
  thetaFlightT: double
  thetaL: double
  totWeight: double
  totWeight2: double
  totWeight2_uBDT: double
  totWeight_uBDT: double
  transverseRes: double
  transverseResDmu: double
  u2mu: double
  u2mu_nonuBDTeCut: double
  u2mu_nonuBDTeSel: double
  u2mu_uBDT: double
  u2mu_uBDTeCut: double
  u2mu_uBDTeSel: double
  u2notmu: double
  wCorr: double
  wDkin: double
  wSPD: double
  wTRIG: double
  weightD: double
  weightTRKeff: double
  weightnTRK: double
  wt: double
```
